### ISSUE TITLE
Travis CI не загружает последний коммит

### ISSUE THREAD

**Issue by Vlad340** [Vlad340/costOrderTaxi#2]
Travis CI не загружает последний коммит для проверки.
Прошу помочь.

![Travis](https://user-images.githubusercontent.com/55633083/66799862-82418c00-ef1b-11e9-9ed3-d1f758b02b21.jpg)

**Comment by coursar** [comment]
В таких случаях выбираете Trigger Custom Build и видите ошибку:

![Screenshot from 2019-10-15 13-57-15](https://user-images.githubusercontent.com/3601892/66825826-c3ee2900-ef53-11e9-8fc1-fe9bd1202d55.png)

Т.е. у вас проблема в `.travis.yml`:

```yml
script:
  - mvn clean package
  - mvn -e verify
  after_success:
    - bash <(curl -s https://codecov.io/bash)
```
А должно быть:
```yml
script:
  - mvn clean package
  - mvn -e verify
after_success:
  - bash <(curl -s https://codecov.io/bash)
```
